List skywaAppointments = [
  {
    "UserId": "631432cc2d8dd3b56622976e",
    "ReservationStartTime": "2022-10-04T12:50:00.000Z",
    "ReservationEndTime": "2022-10-04T13:15:00.000Z",
    "ReservationID": "633c286c52eb9b7be2e6eb35",
    "QID": "62c41676b00b4a68943644fa",
    "firstName": "Padma",
    "middleName": "9647",
    "lastName": "#",
    "MemberState": "Not Arrived",
    "Latitude": "null",
    "Longitude": "null",
    "QJoinTime": "2022-10-04T12:34:52.886Z",
    "OriginalETA": "null",
    "LatestETA": "null",
    "MemberQueuePosition": "null",
    "LastReportedLocationTimeStamp": "null",
    "LastReportedLocationAccuracy": "null",
    "NoShowCount": "null",
    "MemberStateUpdateTimeStamp": "null",
    "WaitTime": "null",
    "ReservationType": "Added by Admin",
    "PhoneNumber": "+919647100133",
    "NumberOfPeopleOnReservation": 1,
    "ReservationCreatedTimeStamp": "null",
    "ReservationUpdatedTimeStamp": "null",
    "CompanyName": "Chandrima's Business",
    "LocationName": "Chandrima's Business",
    "Address": "notSet",
    "CompanyLogoURL": "notSet",
    "QName": "Chandrima's Business",
    "AuthorizedUsers": [],
    "arrivedTimeStamp": "null",
    "inFacilityTimeStamp": "null",
    "calledToEnterTimeStamp": "null",
    "completedTimeStamp": "null",
    "dateOfBirth": "null",
    "dependent": [],
    "station": "null",
    "linkedFiles": [],
    "runningLate": "null",
    "availableEarly": false,
    "distanceFromBusinessInMiles": "null",
    "isWebCheckIn": false,
    "slotBookingDetails": {},
    "appointmentTypeId": "62d2fe9028cc4754fecfba6d",
    "providerId": "null",
    "appointmentTypeName": "SQL",
    "reasonForVisit": "",
    "notes": "",
    "paidForReservation": false,
    "delay": "null",
    "dependence": [
      {
        "userId": "631432cc2d8dd3b56622976e",
        "phoneNumber": "+919647100133",
        "firstName": "Padma 9647",
        "middleName": "null",
        "lastName": "null",
        "suffix": "null",
        "image": "null",
        "email": "null",
        "city": "null",
        "Country": "null",
        "address": "null",
        "sex": "null",
        "birthday": "null",
        "height": "0.0",
        "weight": "0"
      }
    ],
    "profileFormResponse": {
      "formPdfEmailed": false,
      "_id": "632e048ba79d015dfcf174cd",
      "businessId": "62c41676b00b4a68943644fa",
      "userId": "631432cc2d8dd3b56622976e",
      "formId": "630a223691a380077b8c17da",
      "timeStamp": "2022-09-23 19:10:02.350972Z",
      "responseData": {
        "Profile Picture": null,
        "Name": "Padma 9647 #",
        "Address": null,
        "Phone": "+919647100133",
        "Email": null,
        "Birthday": null,
        "Anniversary": null,
        "Notes": null
      },
      "__v": 0
    }
  },
  {
    "UserId": "6321a669490fc07e8c2510c9",
    "ReservationStartTime": "2022-10-05T14:30:00.000Z",
    "ReservationEndTime": "2022-10-05T15:05:00.000Z",
    "ReservationID": "633ae37b5ac21738b63a4c78",
    "QID": "62c41676b00b4a68943644fa",
    "firstName": "Padma 7319 ConsumerDependent",
    "middleName": " ",
    "lastName": " ",
    "MemberState": "Not Arrived",
    "Latitude": "null",
    "Longitude": "null",
    "QJoinTime": "2022-10-03T13:28:27.357Z",
    "OriginalETA": "null",
    "LatestETA": "null",
    "MemberQueuePosition": "null",
    "LastReportedLocationTimeStamp": "null",
    "LastReportedLocationAccuracy": "null",
    "NoShowCount": "null",
    "MemberStateUpdateTimeStamp": "null",
    "WaitTime": "null",
    "ReservationType": "Added by Admin",
    "PhoneNumber": "+917319439725",
    "NumberOfPeopleOnReservation": 1,
    "ReservationCreatedTimeStamp": "null",
    "ReservationUpdatedTimeStamp": "null",
    "CompanyName": "Chandrima's Business",
    "LocationName": "Chandrima's Business",
    "Address": "notSet",
    "CompanyLogoURL": "notSet",
    "QName": "Chandrima's Business",
    "AuthorizedUsers": [],
    "arrivedTimeStamp": "null",
    "inFacilityTimeStamp": "null",
    "calledToEnterTimeStamp": "null",
    "completedTimeStamp": "null",
    "dateOfBirth": "null",
    "dependent": [],
    "station": "null",
    "linkedFiles": [],
    "runningLate": "null",
    "availableEarly": false,
    "distanceFromBusinessInMiles": "null",
    "isWebCheckIn": false,
    "slotBookingDetails": {},
    "appointmentTypeId": "62d2fea228cc4754fecfba76",
    "providerId": "null",
    "appointmentTypeName": "Homeopathy",
    "reasonForVisit": "",
    "notes": "",
    "paidForReservation": false,
    "delay": "null",
    "dependence": [
      {
        "userId": "6321a6d9490fc07e8c2510eb",
        "phoneNumber": "null",
        "firstName": "Padma",
        "middleName": "7319",
        "lastName": "ConsumerDependent",
        "suffix": "null",
        "image": "null",
        "email": "",
        "city": "null",
        "Country": "null",
        "address": "",
        "sex": "null",
        "birthday": "null",
        "height": "0.0",
        "weight": "0"
      }
    ],
    "profileFormResponse": null
  },
  {
    "UserId": "6321a669490fc07e8c2510c9",
    "ReservationStartTime": "2022-10-05T15:22:01.166Z",
    "ReservationEndTime": "2022-10-05T15:52:01.166Z",
    "ReservationID": "633da12752eb9b7be2e6eefd",
    "QID": "62c41676b00b4a68943644fa",
    "firstName": "AB",
    "middleName": " ",
    "lastName": " ",
    "MemberState": "Not Arrived",
    "Latitude": "null",
    "Longitude": "null",
    "QJoinTime": "2022-10-05T15:22:15.705Z",
    "OriginalETA": "null",
    "LatestETA": "null",
    "MemberQueuePosition": "null",
    "LastReportedLocationTimeStamp": "null",
    "LastReportedLocationAccuracy": "null",
    "NoShowCount": "null",
    "MemberStateUpdateTimeStamp": "null",
    "WaitTime": "null",
    "ReservationType": "Added by Admin",
    "PhoneNumber": "+917319439725",
    "NumberOfPeopleOnReservation": 1,
    "ReservationCreatedTimeStamp": "null",
    "ReservationUpdatedTimeStamp": "null",
    "CompanyName": "Chandrima's Business",
    "LocationName": "Chandrima's Business",
    "Address": "notSet",
    "CompanyLogoURL": "notSet",
    "QName": "Chandrima's Business",
    "AuthorizedUsers": [],
    "arrivedTimeStamp": "null",
    "inFacilityTimeStamp": "null",
    "calledToEnterTimeStamp": "null",
    "completedTimeStamp": "null",
    "dateOfBirth": "null",
    "dependent": [],
    "station": "null",
    "linkedFiles": [],
    "runningLate": "null",
    "availableEarly": false,
    "distanceFromBusinessInMiles": "null",
    "isWebCheckIn": false,
    "slotBookingDetails": {},
    "appointmentTypeId": "62c41679b00b4a6894364502",
    "providerId": "null",
    "appointmentTypeName": "default",
    "reasonForVisit": "",
    "notes": "",
    "paidForReservation": false,
    "delay": "null",
    "dependence": [
      {
        "userId": "632ab1cfae242e1d88dc3788",
        "phoneNumber": "null",
        "firstName": "AB",
        "middleName": "null",
        "lastName": "null",
        "suffix": "null",
        "image": "null",
        "email": "null",
        "city": "null",
        "Country": "null",
        "address": "null",
        "sex": "null",
        "birthday": "null",
        "height": "0.0",
        "weight": "0"
      }
    ],
    "profileFormResponse": null
  }
];
